version: "3.9"
services:

  api:
    image: ozysouza/fast-api
    depends_on:
      - db
    ports:
      - "80:8000"
    env_file:
      - ./.env

  db:
    image: postgres
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
